### PR TITLE
Add EdgeeDatalayer Head Injection

### PR DESCRIPTION
**Pull request by Jer1605**
### Summary of Changes

This update introduces a more dynamic and flexible implementation for injecting the `EdgeeDataLayer` script into the `<head>` element. The component now automatically handles script injection via the DOM, ensuring compatibility with server components and a more streamlined integration process.

### Key Changes
- **Dynamic Script Injection:** The `EdgeeDataLayer` script is now dynamically injected into the `<head>` element using `useEffect`, ensuring it is always available and up-to-date.
- **Simplified Usage:** Removed the need for direct rendering of the script tag in the component tree, reducing potential duplication or rendering issues.
- **Error Handling:** Robust error handling ensures that invalid data is logged appropriately without disrupting the application flow.

### Advantages
- **Optimized for Server and Client Components :** Fully compatible with server-rendered components in Next.js, leveraging the client-side lifecycle for script management. Also compatible with React.js
- **Clean and Maintainable:** Simplifies integration by handling the script injection seamlessly in the background.
- **Future-Proof:** Prepares the SDK for more advanced use cases by decoupling the script injection from the component's rendering logic.

### CODE REVIEW

**Comment by Jer1605** [comment]
Another option would be to enhance the SDK with a store that could be consumed by two components. This is a more React-oriented approach, both approaches are valid, but this one adds some weight to our SDK and is a bit more complex for the final user.

It would look like something like:
```js
'use client';

import { create } from 'zustand';
import { useEffect } from 'react';
import { EdgeeDataLayerObject } from 'react-edgee';

type EdgeeDataLayerStore = {
  dataLayer: EdgeeDataLayerObject;
  setDataLayer: (data: EdgeeDataLayerObject) => void;
};

const useEdgeeDataLayerStore = create<EdgeeDataLayerStore>((set) => ({
  dataLayer: {},
  setDataLayer: (data: EdgeeDataLayerObject) => {
    set(() => ({ dataLayer: data }));
  },
}));

const EdgeeDatalayer = ({ data }: {data: EdgeeDataLayerObject}): JSX.Element => {
  const { setDataLayer } = useEdgeeDataLayerStore();
  useEffect(() => {
    setDataLayer(data);
  }, [data]);
  return <></>;
};

const EdgeTagDataLayer = (): JSX.Element => {
  const { dataLayer: dataLayerStore } = useEdgeeDataLayerStore();
  let dataLayer = '';
  try {dataLayer = JSON.stringify(dataLayerStore);
  } catch (error) {return <></>;}
  return (
    <script
      id="__EDGEE_DATA_LAYER__"
      type="application/json"
      dangerouslySetInnerHTML={{ __html: dataLayer }}
    ></script>
  );
};

export {EdgeeDatalayer, EdgeTagDataLayer};
```

**Review by SachaMorard — COMMENTED** [review]
@Jer1605 I'm really sceptical about this approach. Are you sure the Data Layer will be injected both **server side** AND **client side** ?

**Comment by alexcasalboni** [comment]
If it works, I'd prefer the simple approach to keep the current developer experience (without adding more complexity for customers).

**Comment by Jer1605** [comment]
hey @SachaMorard @alexcasalboni , I chose a hybrid approach where useEffect dynamically injects the Data Layer into the <head> on the client side after hydration, ensuring updates happen in real-time while keeping the router functional and the app smooth. I’ll test more tomorrow, especially compatibility with the SDK, to confirm if it detects Data Layer changes. If not, we might need to remove and re-inject the script on SPA page change. In another company I worked at, for similar SPA/SDK integrations, we detected page changes and triggered a re-run of  som features of the SDK.

Handling this entirely via SSR seams very compromised while keeping SPA behavior, as the server-rendered HTML is static once hydrated, and any dynamic updates would require a full page refresh, breaking the seamless SPA experience.

**Comment by alexcasalboni** [comment]
I feel like I don't fully understand how Next.js works, but do we already have this problem today? I mean, if the page change is fully client-side and there's no HTTP request through the Edgee proxy (and the JS SDK doesn't notice the Data Layer change), are we already missing some events?

**Comment by Jer1605** [comment]
Hey @alexcasalboni , after discussing with @SachaMorard, the challenge here is that we need the EdgeeDataLayer to be present both during SSR and on the client side. This is because Edgee will parse the page at the edge, and if it doesn't encounter an EdgeeDataLayer in the <head>, it will need to parse the entire page, which we want to avoid.

Using variables like metadata could make this work, as they are accessible both server-side and client-side, but I’d also like to investigate a 100% React-SDK approach for flexibility and consistency.

PS: I'll close this PR, it brang some great discussions at least 👍

**Pull request closed without merging**
